on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest
    with:
      super_secret: ${{ secrets.build-token}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
